public class MultiStaticBlock 
{
    public static void display() 
    {
        System.debug('Welcome to main method');
    }
    Static
    {
        System.debug('Welcome to First Static Block');
        System.debug('I am static Block');
    }
    Static
    {
        System.debug('Welcome to Second Static Block');
     }
    Static
    {
        System.debug('Welcome to Third Static Block');
    }
    

}