public class RelationDemo {
    public static void display()
    {     
        Integer num1=20;
        Integer num2=30;
        if(num1==num2)
            if(num1==num2)
        {
            System.debug('num1 and num2 are equal');
        }
        else
        {
            System.debug('num1 is not equal to num2');
        }
        if(num1>num2)
        {
            System.debug('num1 is greater than num2');
        }
        else
        {
            System.debug('num2 is greater than num1');
        }   
        if(num1!=num2)
        {
            System.debug('num1 is not equal to num2');
        }
        else
        {
            System.debug('num1 and num2 are equal');
        }
    }
}